/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.db.Tareas.gui;

import com.db.Tareas.domain.Estados;
import com.db.Tareas.domain.Tarea;
import com.db.Tareas.excepciones.TareaException;
import com.db.Tareas.servicios.TareasService;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class VentanaTarea extends javax.swing.JFrame {

    
    //private Estados[] estado;
    private int num, row1, row2, row3;
    private String descripcion, estadoTarea;
    private static String[] estado = {"TO DO", "IN PROGRESS", "DONE"};
    private TareasService ts = null;
    
    public VentanaTarea() {
        initComponents();
        inicializarTarea(estado);
    }

/**
     * Creates new form ventanaTarea
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableToDo = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProgress = new javax.swing.JTable();
        btnInsert2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDone = new javax.swing.JTable();
        btnAddTarea = new javax.swing.JButton();
        btnModificaTarea = new javax.swing.JButton();
        btnEliminaTarea = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        lblToDo = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        lblDone = new javax.swing.JLabel();
        btnArchivado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CANVAS_TASK");

        jTableToDo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableToDo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableToDo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableToDo);

        btnInsert.setText(">");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jTableProgress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProgress.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTableProgress);

        btnInsert2.setText(">");
        btnInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert2ActionPerformed(evt);
            }
        });

        jTableDone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDone.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTableDone);

        btnAddTarea.setText("Agregar Tarea");
        btnAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTareaActionPerformed(evt);
            }
        });

        btnModificaTarea.setText("Modificar Tarea");
        btnModificaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaTareaActionPerformed(evt);
            }
        });

        btnEliminaTarea.setText("Elimina Tarea");
        btnEliminaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaTareaActionPerformed(evt);
            }
        });

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnBack2.setText("<");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        lblToDo.setText("To Do");

        lblProgress.setText("In Progress");

        lblDone.setText("Done");

        btnArchivado.setText("Archivado");
        btnArchivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsert)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsert2)
                    .addComponent(btnBack2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnAddTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(btnModificaTarea)
                .addGap(233, 233, 233)
                .addComponent(btnEliminaTarea)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblToDo)
                .addGap(243, 243, 243)
                .addComponent(lblProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDone)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnArchivado)
                .addGap(423, 423, 423))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnInsert2)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnInsert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblToDo)
                                    .addComponent(lblProgress)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDone)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminaTarea)
                    .addComponent(btnModificaTarea)
                    .addComponent(btnAddTarea))
                .addGap(33, 33, 33)
                .addComponent(btnArchivado)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTareaActionPerformed
        new VentanaTareaAdd(this).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddTareaActionPerformed

    private void btnModificaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaTareaActionPerformed
        this.row1 = jTableToDo.getSelectedRow();
        this.row2 = jTableProgress.getSelectedRow();
        this.row3 = jTableDone.getSelectedRow();
        
        if(this.row1 != -1){
            this.descripcion = (String) (jTableToDo.getModel().getValueAt(row1, 1));
            this.estadoTarea = (String) (jTableToDo.getModel().getValueAt(row1, 2));
            new VentanaTareaModificar(this, this.descripcion, this.estadoTarea).setVisible(true);
            dispose();
        }
        
        if(this.row2 != -1){
            this.descripcion = (String) (jTableProgress.getModel().getValueAt(this.row2, 1));
            this.estadoTarea = (String) (jTableProgress.getModel().getValueAt(this.row2, 2));
            new VentanaTareaModificar(this, this.descripcion, this.estadoTarea).setVisible(true);
            dispose();
        }
        
        if(this.row3 != -1){
            this.descripcion = (String) (jTableDone.getModel().getValueAt(this.row3, 1));
            this.estadoTarea = (String) (jTableDone.getModel().getValueAt(this.row3, 2));
            new VentanaTareaModificar(this, this.descripcion, this.estadoTarea).setVisible(true);
        }
    }//GEN-LAST:event_btnModificaTareaActionPerformed

    private void btnEliminaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaTareaActionPerformed
        this.row1 = jTableToDo.getSelectedRow();
        this.row2 = jTableProgress.getSelectedRow();
        this.row3 = jTableDone.getSelectedRow();
        process(this.row1,jTableToDo);
        process(this.row2,jTableProgress);
        process(this.row3,jTableDone);
    }//GEN-LAST:event_btnEliminaTareaActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        //String descripcionNuevo, estadoNuevo;
        ts = new TareasService();
        this.row1 = jTableToDo.getSelectedRow();
        try{
            if(row1 != -1){
                this.descripcion = (String) (jTableToDo.getModel().getValueAt(this.row1, 1));
                this.estadoTarea = (String) (jTableToDo.getModel().getValueAt(this.row1, 2));
                ts.modificaTarea(this.descripcion, estado[1] , this.descripcion, this.estadoTarea);
                jTableToDo.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[0])));
                jTableProgress.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[1])));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ts = new TareasService();
        this.row1 = jTableProgress.getSelectedRow();
        try{
            if(this.row1 != -1){
                this.descripcion = (String) (jTableProgress.getModel().getValueAt(this.row1, 1));
                this.estadoTarea = (String) (jTableProgress.getModel().getValueAt(this.row1, 2));
                ts.modificaTarea(this.descripcion, estado[0] , this.descripcion, this.estadoTarea);
                jTableToDo.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[0])));
                jTableProgress.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[1])));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert2ActionPerformed
        this.ts = new TareasService();
        this.row1 = jTableProgress.getSelectedRow();
        try{
            if(this.row1 != -1){
                this.descripcion = (String) (jTableProgress.getModel().getValueAt(this.row1, 1));
                this.estadoTarea = (String) (jTableProgress.getModel().getValueAt(this.row1, 2));
                ts.modificaTarea(this.descripcion, estado[2], this.descripcion, this.estadoTarea);
                jTableProgress.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[1])));
                jTableDone.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[2])));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnInsert2ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        this.ts = new TareasService();
        this.row1 = jTableDone.getSelectedRow();
        try{
            if(this.row1 != -1){
                this.descripcion = (String) (jTableDone.getModel().getValueAt(this.row1, 1));
                this.estadoTarea = (String) (jTableDone.getModel().getValueAt(row1, 2));
                ts.modificaTarea(this.descripcion, estado[1], this.descripcion, this.estadoTarea);
                jTableProgress.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[1])));
                jTableDone.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[2])));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnArchivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivadoActionPerformed
        this.ts = new TareasService();
              
//        try {
//            fil = new Fichero(jTextFieldNameFile.getText());
//            fil2 = fil;
//            
//            Runnable r = new Runnable(){
//                @Override
//                public void run() {
//                    fil2.numerosDelCuatroAlDos();
//                }
//            };
//            
//            Thread h1 = new Thread(fil);
//            Thread h2 = new Thread(r);
//            
//            h1.start();
//            h2.start();
//            
//            h1.join();
//            h2.join();
//            JOptionPane.showMessageDialog(this, "HE TERMINADO");
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ventanaTH.class.getName()).log(Level.SEVERE, null, ex);
//        }
  
        try {
            ts.altaArchivadorDone();
            jTableDone.setModel(new TareaDataModel(ts.getListaTareasPorEstado(estado[2])));
            JOptionPane.showMessageDialog(this, "Registro guardado");
        } catch (TareaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnArchivadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTarea;
    private javax.swing.JButton btnArchivado;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnEliminaTarea;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsert2;
    private javax.swing.JButton btnModificaTarea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableDone;
    private javax.swing.JTable jTableProgress;
    private javax.swing.JTable jTableToDo;
    private javax.swing.JLabel lblDone;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblToDo;
    // End of variables declaration//GEN-END:variables

    public void inicializarTarea(String[] status) {
        try{
            this.ts = new TareasService();
            List<Tarea> lista1 = this.ts.getListaTareasPorEstado(status[0]);
            List<Tarea> lista2 = this.ts.getListaTareasPorEstado(status[1]);
            List<Tarea> lista3 = this.ts.getListaTareasPorEstado(status[2]);
            if( (lista1.isEmpty()) && (lista2.isEmpty()) && (lista3.isEmpty()) ){
                JOptionPane.showConfirmDialog(this, "No hay Tareas");
            }
            else{
                jTableToDo.setModel(new TareaDataModel(lista1));
                jTableProgress.setModel(new TareaDataModel(lista2));
                jTableDone.setModel(new TareaDataModel(lista3));
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    public void process(int row, JTable caja){
        this.ts = new TareasService();
        try{
            if(row != -1){
                //obtengo el valor de la columna 1
                this.descripcion = (String) (caja.getModel().getValueAt(row, 1));
                ts.bajaTarea(descripcion);
                this.dispose();
                new VentanaTarea().setVisible(true);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
    
}
